# Generated by Django 3.1 on 2020-08-29 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='historical_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yahoo_id', models.CharField(max_length=50)),
                ('open_price', models.FloatField(null=True)),
                ('close_price', models.FloatField(null=True)),
                ('high_price', models.FloatField(null=True)),
                ('low_price', models.FloatField(null=True)),
                ('spot_date', models.DateField(null=True)),
                ('price_change_1d', models.FloatField(null=True)),
                ('price_change_2d', models.FloatField(null=True)),
                ('price_change_5d', models.FloatField(null=True)),
                ('price_change_10d', models.FloatField(null=True)),
                ('price_change_15d', models.FloatField(null=True)),
                ('price_change_30d', models.FloatField(null=True)),
            ],
            options={
                'verbose_name': 'historical price',
            },
        ),
    ]
