# Generated by Django 3.1 on 2020-08-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historical_price', '0002_historical_price_dividend'),
    ]

    operations = [
        migrations.AddField(
            model_name='historical_price',
            name='volume',
            field=models.FloatField(null=True),
        ),
    ]
