# Generated by Django 3.1 on 2020-09-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historical_price', '0005_balance_sheet_income_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='historical_price',
            name='ranking_change_5d',
            field=models.FloatField(null=True),
        ),
    ]
