# Generated by Django 3.1 on 2020-09-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='strategy_backtested',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('yahoo_id', models.CharField(max_length=100)),
                ('param_1', models.FloatField()),
                ('param_2', models.FloatField()),
                ('param_4', models.FloatField()),
                ('param_3', models.FloatField()),
            ],
            options={
                'verbose_name': 'Strategy',
            },
        ),
    ]
