# Generated by Django 3.1 on 2020-09-13 06:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy_backtested',
            name='buy_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strategy_backtested',
            name='buy_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strategy_backtested',
            name='sell_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strategy_backtested',
            name='sell_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
