# Generated by Django 3.1 on 2020-09-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0002_auto_20200913_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy_backtested',
            name='buy_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='strategy_backtested',
            name='buy_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='strategy_backtested',
            name='param_1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='strategy_backtested',
            name='param_2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='strategy_backtested',
            name='param_3',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='strategy_backtested',
            name='param_4',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='strategy_backtested',
            name='sell_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='strategy_backtested',
            name='sell_price',
            field=models.FloatField(null=True),
        ),
    ]
