# Generated by Django 3.1 on 2020-09-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0003_auto_20200913_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strategy_backtested',
            options={'verbose_name': 'technical_indicator strategy'},
        ),
        migrations.AddField(
            model_name='strategy_backtested',
            name='indicator_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strategy_backtested',
            name='param_5',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='strategy_backtested',
            name='param_6',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='strategy_backtested',
            name='param_7',
            field=models.FloatField(null=True),
        ),
    ]
