# Generated by Django 3.1 on 2020-09-27 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0004_auto_20200927_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strategy_backtested',
            options={'verbose_name': 'Strategy'},
        ),
    ]
