# Generated by Django 3.1 on 2020-08-29 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='securitydescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50)),
                ('yahoo_id', models.CharField(max_length=50)),
                ('ticker', models.CharField(max_length=50)),
                ('ric', models.CharField(max_length=50)),
                ('sector_level_1', models.CharField(max_length=100)),
                ('sector_level_2', models.CharField(max_length=100)),
                ('industry_level_1', models.CharField(max_length=100)),
                ('industry_level_2', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=10)),
                ('rating_SP', models.CharField(max_length=20)),
                ('rating_Fish', models.CharField(max_length=20)),
                ('rating_Moodys', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'security description',
            },
        ),
    ]
