# Generated by Django 3.1 on 2020-08-30 08:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('referential', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitydescription',
            name='benchmark_1',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='securitydescription',
            name='benchmark_2',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='securitydescription',
            name='benchmark_3',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='securitydescription',
            name='market_place',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='securitydescription',
            name='product_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='securitydescription',
            name='yahoo_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
