# Generated by Django 3.1 on 2020-09-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referential', '0003_auto_20200906_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitydescription',
            name='market_cap',
            field=models.FloatField(null=True),
        ),
    ]
