# Generated by Django 3.1 on 2020-09-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referential', '0005_secutity_earning'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitydescription',
            name='isin',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
