# Generated by Django 3.1 on 2020-09-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referential', '0006_securitydescription_isin'),
    ]

    operations = [
        migrations.CreateModel(
            name='economic_calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_name', models.CharField(max_length=50, unique=True)),
                ('importance', models.CharField(max_length=50)),
                ('estimated', models.FloatField(null=True)),
                ('realized', models.FloatField(null=True)),
            ],
            options={
                'verbose_name': 'Economic calendar',
            },
        ),
        migrations.AlterModelOptions(
            name='securitydescription',
            options={'verbose_name': 'Security description'},
        ),
        migrations.AlterModelOptions(
            name='secutity_earning',
            options={'verbose_name': 'Earning Calendar'},
        ),
        migrations.AddField(
            model_name='secutity_earning',
            name='earning_estimated',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='secutity_earning',
            name='earning_realized',
            field=models.FloatField(null=True),
        ),
    ]
